export const START_GAME = 'START_GAME';
export const MOVE_DOWN = 'MOVE_DOWN';
export const MOVE_RIGHT = 'MOVE_RIGHT';
export const MOVE_LEFT = 'MOVE_LEFT';
export const ROTATE_DOWN = 'ROTATE_DOWN';
export const ROTATE_UP = 'ROTATE_UP';
export const GAME_OVER = 'GAME_OVER';
export const RESET_GAME_STATE = 'RESET_GAME_STATE';

export const FETCH_SCORES_REQUEST = "FETCH_SCORES_REQUEST";
export const FETCH_SCORES_SUCCESS = "FETCH_SCORES_SUCCESS";
export const FETCH_SCORES_ERROR = "FETCH_SCORES_ERROR";
export const SEND_SCORE_SUCCESS = "SEND_SCORE_SUCCESS";
export const SEND_SCORE_ERROR = "SEND_SCORE_ERROR";
